development;
	bucket: krf-dev
	access_key_id: AKIAIO3T5UNLGO4JYCBQ
	secret_access_key: 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
production;
	bucket: krf-pro
	access_key_id: AKIAIO3T5UNLGO4JYCBQ
	secret_access_key: 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